apiVersion: apps/v1
kind: Deployment
metadata:
    name: addict
    labels:
        app: addict
spec:
    replicas: 1
    selector:
        matchLabels:
            app: addict
    template:
        metadata:
            labels:
                app: addict
        spec:
            containers:
                - name: addict
                  image: makingsenseinfo/addict:0.5.3
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 8080
                  env:
                      - name: GITHUB_TOKEN
                        value: "XXX"
