name: Deploy DDI resources to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'resources/**'

jobs:
  deploy-resources:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up gh-pages branch
      run: |
        git fetch origin gh-pages
        git checkout gh-pages || git checkout --orphan gh-pages
        git rm -rf . --ignore-unmatch
        echo "gh-pages branch prepared."

    - name: Copy resources if they exist
      run: |
        if [ -d "./resources" ]; then
          cp -r ./resources/* ./
          echo "Resources copied to gh-pages branch."
        else
          echo "No resources found to deploy."
        fi

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Deploy DDI resources to GitHub Pages" || echo "No changes to commit."
        git push origin gh-pages --force
