name: Deploy DDI resources to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'resources/**'

jobs:
  deploy-resources:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Clear gh-pages branch
      run: |
        git fetch origin gh-pages
        git checkout gh-pages || git checkout --orphan gh-pages
        git rm -rf . --ignore-unmatch
        echo "gh-pages branch cleared."

    - name: Copy new resources
      run: |
        cp -r ./resources/* ./
        echo "Resources copied to gh-pages branch."

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Deploy DDI resources to GitHub Pages"
        git push origin gh-pages --force